/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Paulo
 */
public class JFrmGeradorDeRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form JFrmGeradorDeRelatorios
     */
    public JFrmGeradorDeRelatorios() {
        initComponents();
        ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("/img/icone.png"));
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AtividadeRelatoriosPU").createEntityManager();
        queryJogador = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("select p from Jogador p");
        listJogador = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryJogador.getResultList());
        queryJogo = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("select g from Jogo g");
        listJogo = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryJogo.getResultList());
        queryLojaDeJogo = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("select a from Lojadejogos a");
        listLojaDeJogo = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryLojaDeJogo.getResultList());
        queryCompra = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("select c from Compra c");
        listCompra = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryCompra.getResultList());
        queryUsuario = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("select u from Usuario u");
        listUsuario = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryUsuario.getResultList());
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerador de Relatórios - Games Report");
        setBackground(new java.awt.Color(102, 102, 255));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerador de Relatórios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/game-store_gerador.png"))); // NOI18N
        jButton2.setText("Relatório de Lojas de Jogos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra_gerador.png"))); // NOI18N
        jButton5.setText("Relatório de Compras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gamer_gerador.png"))); // NOI18N
        jButton1.setText("Relatório de Jogadores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/game_gerador.png"))); // NOI18N
        jButton3.setText("Relatório de Jogos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario_gerador.png"))); // NOI18N
        jButton4.setText("Relatório de Usuários");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
//Criando uma variável do tipo JRBeanCollectionDataSource (uma classe de relatórios). O JRBeanCollectionDataSource converte o resultado da sua lista de resultado do
        //banco dados em uma fonte de dados para imprimí-los no relatório.
        
//        ==Parâmetros do JRBeanCollectionDataSource() -> JRBeanCollectionDataSource(lista de resultados do banco de dados, isUseFieldDescription)
//        listCompra -> usando a lista de resultados da tabela compra do banco de dados
//        false -> não iremos usar o campo de descrição
//        
        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(listCompra, false);
        try {
            //Criando uma variável do tipo JasperPrint (uma classe de relatórios) que preenche o relatório com os dados desejados
            
//            ==Parâmetros do JasperFillManager.fillReport() -> JasperFillManager.fillReport("endereçoDoRelatorio", parâmetros, dados a serem inseridos)
//            "./relatorios/relatorio_geral.jasper" -> endereço do relatório de 4 tabelas com relaçaõ ao JFrame que estamos utilizando
//            null -> não iremos enviar nenhum parâmetro
//            dados -> dados guardados na variável dados, do tipo JRBeanCollectionDataSource
//            
            JasperPrint relatorio = JasperFillManager.fillReport("./relatorios/relatorio_geral.jasper", null, dados);
            //Criando uma variável do tipo JasperViewer (uma classe de relatorio). O JasperViewer serve para poder visualizar o relatório
            
//            ==Parâmetro do JasperViewer() -> JasperViewer(JasperPrint, isExitOnClose)
//            relatorio -> variável JasperPrint, responsável por imprimir os dados no relatório
//            false - não sair do programa ao fechar o relatório
//            
            JasperViewer visualizador = new JasperViewer(relatorio, false);
            //Mostrando o relatório (deixando ele visíveel)
            visualizador.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(listUsuario, false);
        try {
            
            JasperPrint relatorio = JasperFillManager.fillReport("./relatorios/relatorioUsuarios.jasper", null, dados);
            
//            
            JasperViewer visualizador = new JasperViewer(relatorio, false);
        
            visualizador.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(Level.SEVERE, null, ex); //
        }
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(listJogador, false);
        try {
            
            JasperPrint relatorio = JasperFillManager.fillReport("./relatorios/relatorioWizard1.jasper", null, dados);
            
//            
            JasperViewer visualizador = new JasperViewer(relatorio, false);
        
            visualizador.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(listJogo, false);
        try {
            
            JasperPrint relatorio = JasperFillManager.fillReport("./relatorios/relatorioWizard2.jasper", null, dados);
            
//            
            JasperViewer visualizador = new JasperViewer(relatorio, false);
        
            visualizador.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(Level.SEVERE, null, ex); //
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JRBeanCollectionDataSource dados = new JRBeanCollectionDataSource(listLojaDeJogo, false);
        try {
            JasperPrint relatorio = JasperFillManager.fillReport("./relatorios/reportLojaDeJogos.jasper", null, dados);
            JasperViewer visualizador = new JasperViewer(relatorio, false);
            visualizador.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmGeradorDeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmGeradorDeRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel5;
    private java.util.List<Compra> listCompra;
    private java.util.List<Jogador> listJogador;
    private java.util.List<Jogo> listJogo;
    private java.util.List<Lojadejogos> listLojaDeJogo;
    private java.util.List<Usuario> listUsuario;
    private javax.persistence.Query queryCompra;
    private javax.persistence.Query queryJogador;
    private javax.persistence.Query queryJogo;
    private javax.persistence.Query queryLojaDeJogo;
    private javax.persistence.Query queryUsuario;
    // End of variables declaration//GEN-END:variables
}
